Separation = 18 # length (in relative int) / separation
Acceleration = 1
StartVelocity = 0
MaxVelocity = 4
Probability = 0.8  # for city - 0.5; for highway - 0.8 Probability of accidentally stopping of car (1 - value)
StartPeriodLow = 10
StartPeriodHigh = 30
PeriodStopFlow = 3
IngnoringSupreme = 0.3
Scale = 100000 # dangle (longitude) * scale
ForbiddenHighways = ["cycleway", "construction", "busway", "motorway", "pedestrian", "track", "escape", "footway", "bridleway", "steps", "corridor", "path"]
NameCarsFile = "data/cars.json"
NameMapFile = "data/map.json"
NameOsmFile = "data/map_small.osm"