Separation = 1
Acceleration = 1
StartVelocity = 0
MaxVelocity = 3
Probability = 0.5  # for city - 0.5; for highway - 0.3
StartPeriodLow = 10
StartPeriodHigh = 50
Scale = 100000
NCars = 1
ForbiddenHighways = ["cycleway", "construction", "busway", "motorway", "motorway_link", "pedestrian", "track", "escape", "footway", "bridleway", "steps", "corridor", "path"]
NameCarsFile = "data/cars.json"
NameMapFile = "data/map.json"
NameOsmFile = "data/map_small.osm"