Separation = 1
Acceleration = 1
StartVelocity = 0
MaxVelocity = 3
Probability = 0.5  # for city - 0.5; for highway - 0.3
StartPeriodLow = 10
StartPeriodHigh = 50
NameCarsFile = "../data/cars.json"
NameMapFile = "../data/map.json"
NameOsmFile = "../data/map_big.osm"